name: admin_app
description: Sinar Berkat Furniture - Admin App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.1

  # Secure storage untuk token
  flutter_secure_storage: ^9.0.0

  # Navigation
  go_router: ^13.0.0

  # UI
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1

  # Image picker untuk upload foto produk
  image_picker: ^1.0.7

  supabase_flutter: ^2.0.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true